[tool.poetry]
name = "odometry"
version = "0.1.0"
description = ""
authors = ["David Hunt <dmh89@duke.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
numpy = "^1.25"
scikit-learn = "^1.3.2"
SciPy = "^1.11.4"
matplotlib = "^3.8.2"
tqdm = "^4.66.1"
ipywidgets = "^8.1.1"
jupyter = "^1.0.0"
pytest = "^7.4.4"
imageio = {extras = ["ffmpeg"], version = "^2.33.1"}
addict = "^2.4.0"
pandas = "^2.1.4"
opencv-python = ">4.7, <4.9.0.80"
poetry-dotenv-plugin = "^0.2.0"

# Optional dependencies
cpsl_datasets = {path="./submodules/cpsl_datasets/", develop = true, optional = true}
mmwave_radar_processing = {path="./submodules/mmwave_radar_processing/", develop = true, optional = true}
mmwave_model_integrator = {path="./submodules/mmwave_model_integrator/", develop=true, optional = true}
radcloud = {path="./submodules/radcloud/", develop = true, optional = true}
radarhd = {path="./submodules/radarhd/", develop=true, optional = true}
lib-avstack-core = {path="./submodules/lib-avstack-core/",develop=true, optional = true}
geometries = {path="./submodules/geometries/",develop=true, optional = true}

[tool.poetry.group.torch.dependencies]
torch = "^2.4.0"
torchvision = "^0.19.0"
torchaudio = "^2.4.0"
torchsummary = "^1.5.1"
torch-geometric = "^2.6.1"

[tool.poetry.extras]
submodules = [
    "cpsl_datasets",
    "mmwave_radar_processing",
    "mmwave_model_integrator",
    "radcloud",
    "radarhd",
    "lib-avstack-core",
    "geometries"
]

[tool.poetry.group.dev.dependencies]
ipywidgets = "^8.1.1"
jupyter = "^1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
bandit = "^1.7"
black = "~22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
